FROM scylladb/scylla:6.1.1

RUN \
    export DEBIAN_FRONTEND=noninteractive \
    && apt-get update -y -q \
    && apt-get install -y \
       iproute2 vim fish nmon htop less \
    && rm -rf /var/lib/apt/lists/*

COPY varia/"*" /tmp/
RUN python3 /tmp/edit_scylla_conf.py
