name: "dali"
backend: "dali"
max_batch_size: 256
input [
  {
    name: "Reader"
    data_type: TYPE_UINT64
    dims: [ 2 ]
  }
]
output [
  {
    name: "DALI_OUTPUT_0"
    data_type: TYPE_UINT8
    dims: [ 224, 224, 3 ]
  },
  {
    name: "DALI_OUTPUT_1"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
