FROM harbor.crs4.it/cesco-public/cassandra-dali-plugin:pap

# if needed, change ids
USER root
ENV EXT_UID 1000
ENV EXT_GID 1000
RUN usermod -u ${EXT_UID} user
RUN groupmod -g ${EXT_GID} user
RUN chown -R ${EXT_UID}:${EXT_GID} /cassandra/ /home/user/ /spark/ /data/

# install deps for testing
RUN pip install torchdata mosaicml-streaming

USER user
